"""empty message

Revision ID: 57d811cffe94
Revises: 7844dd65a476
Create Date: 2022-02-24 18:40:01.828380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d811cffe94'
down_revision = '7844dd65a476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('states_acronym_key', 'states', type_='unique')
    op.drop_constraint('states_name_key', 'states', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('states_name_key', 'states', ['name'])
    op.create_unique_constraint('states_acronym_key', 'states', ['acronym'])
    # ### end Alembic commands ###
