"""empty message

Revision ID: 891471f29af9
Revises: 57d811cffe94
Create Date: 2022-02-24 18:42:17.381617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891471f29af9'
down_revision = '57d811cffe94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('capitals_name_key', 'capitals', type_='unique')
    op.drop_constraint('capitals_state_id_key', 'capitals', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('capitals_state_id_key', 'capitals', ['state_id'])
    op.create_unique_constraint('capitals_name_key', 'capitals', ['name'])
    # ### end Alembic commands ###
